"""add_suggestions

Revision ID: 2f9e4536183c
Revises: 9fface1c79eb
Create Date: 2026-01-30 17:54:57.345996

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2f9e4536183c"
down_revision = "9fface1c79eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proof_suggestions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("explanation", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["proof_pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["proof_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["proof_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("proof_suggestions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proof_suggestions_page_id"), ["page_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_proof_suggestions_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_proof_suggestions_revision_id"),
            ["revision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_proof_suggestions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ix_proof_suggestions_status", ["status"], unique=False)
        batch_op.create_index(
            "ix_proof_suggestions_created_at", ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proof_suggestions", schema=None) as batch_op:
        batch_op.drop_index("ix_proof_suggestions_created_at")
        batch_op.drop_index("ix_proof_suggestions_status")
        batch_op.drop_index(batch_op.f("ix_proof_suggestions_user_id"))
        batch_op.drop_index(batch_op.f("ix_proof_suggestions_revision_id"))
        batch_op.drop_index(batch_op.f("ix_proof_suggestions_project_id"))
        batch_op.drop_index(batch_op.f("ix_proof_suggestions_page_id"))

    op.drop_table("proof_suggestions")
    # ### end Alembic commands ###
