"""add_status_column_to_text

Revision ID: 9fface1c79eb
Revises: 682a19f319bc
Create Date: 2026-01-22 18:37:54.355246

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9fface1c79eb"
down_revision = "682a19f319bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("texts", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
