"""Add RevisionBatch

Revision ID: c6c18d3bdec1
Revises: 8951ab61803e
Create Date: 2025-12-10 20:44:38.318903

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "c6c18d3bdec1"
down_revision = "8951ab61803e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proof_revision_batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proof_revision_batches_user_id"),
        "proof_revision_batches",
        ["user_id"],
        unique=False,
    )

    with op.batch_alter_table("proof_revisions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("batch_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_proof_revisions_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_proof_revisions_batch_id",
            "proof_revision_batches",
            ["batch_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proof_revisions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_proof_revisions_batch_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_proof_revisions_batch_id"))
        batch_op.drop_column("batch_id")

    op.drop_index(
        op.f("ix_proof_revision_batches_user_id"), table_name="proof_revision_batches"
    )
    op.drop_table("proof_revision_batches")
    # ### end Alembic commands ###
