"""Add status column to Project

Revision ID: cedb1d7171ff
Revises: dcd3efd76983
Create Date: 2026-01-17 08:28:42.523023

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "cedb1d7171ff"
down_revision = "dcd3efd76983"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proof_projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=True))

    op.execute("UPDATE proof_projects SET status = 'active' WHERE status IS NULL")

    with op.batch_alter_table("proof_projects", schema=None) as batch_op:
        batch_op.alter_column("status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proof_projects", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
