"""Add many-to-many relationship between Project and ProjectTag

Revision ID: dcd3efd76983
Revises: ec6fb39e6ad5
Create Date: 2026-01-17 05:55:20.010460

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "dcd3efd76983"
down_revision = "ec6fb39e6ad5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "project_tag_association",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["proof_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["project_tags.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_tag_association")
    op.drop_table("project_tags")
    # ### end Alembic commands ###
