"""Add sha256_checksum column to TextExport

Revision ID: ec6fb39e6ad5
Revises: ecae0dec7c3f
Create Date: 2025-12-26 09:18:56.431145

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ec6fb39e6ad5"
down_revision = "ecae0dec7c3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("text_exports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sha256_checksum", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_text_exports_text_id"), ["text_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("text_exports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_text_exports_text_id"))
        batch_op.drop_column("sha256_checksum")

    # ### end Alembic commands ###
